### Products Index
GET http://localhost:3000/products
Authorization: Bearer 

### Products Show
GET http://localhost:3000/products/1

### Products Post
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Potato Chips",
  "price": 3,
  "image_url": "https://images.app.goo.gl/vFcQ6qxAyfXvKiyr6",
  "description": "Crunchy Potato Chips"
}

### Products Update
PATCH localhost:3000/products/1.json

### User generated order
POST http://localhost:3000/orders.json
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 1,
  "quantity": 4,
  "subtotal": 10,
  "tax": 0.9,
  "total": 10.9
}