### Products Index
GET http://localhost:3000/products.json?category=Produce

### Products Show
GET http://localhost:3000/products/1

### Products Create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Potato Chips",
  "price": 3,
  "description": "Crunchy Potato Chips",
  "inventory": 50,
  "supplier_id": 4,
  "image_url": 
}

### Products Update
PATCH localhost:3000/products/1.json
{
  "price": 10
}
### Product Destroy
DELETE http://lo
### User generated order
POST http://localhost:3000/orders.json
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 1,
  "quantity": 4,
  "subtotal": 10,
  "tax": 0.9,
  "total": 10.9
}